---
# Make it enabled-worlds: [] or delete to enable on all worlds
enabled-worlds:
  - world
  - otherworld

# Worlds that plugin won't work, make it disabled-worlds: [] to make it empty
disabled-worlds:
  - disabledworld

# Maximum blocks at once
max-blocks: 32

# Should it damage to players when falling?
# Type 0 for no damage
# 2 HP = 1 Heart
fall-damage: 1 #HP
...
